
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pjhub-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/pjhub.git
    path: gitOps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
