#########################################
# Envoy admin interface
# You will be able to access the Envoy admin Interface on 0.0.0.0:19000      
#########################################
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 19000
