
---
- name: Deploy ArgoCD
  hosts: all
  tasks:
    - name: Add ArgoCD helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: Deploy ArgoCD
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        values_files:
          - argocd/values.yaml

    - name: Apply Application
      kubernetes.core.k8s:
        state: present
        src: argocd/application.yaml
