
---
- name: Deploy infrastructure
  hosts: localhost
  become: yes

  tasks:
    - name: Start docker services
      docker_compose:
        project_src: "../../docker"
        files:
          - docker-compose.yml
        state: present

    - name: Initialize Vault
      command: vault operator init
      environment:
        VAULT_ADDR: "http://0.0.0.0:8200"
      register: vault_init
      
    - name: Configure MinIO
      command: mc config host add myminio http://0.0.0.0:9000 minio minio123
      
    - name: Create MinIO buckets
      command: mc mb myminio/frontend myminio/backend
